const SERVICES={
 Instagram:{icon:'◎',items:[['ig_follow','فالوور اینستاگرام',150000],['ig_like','لایک اینستاگرام',30000],['ig_view','ویو اینستاگرام',20000],['ig_story_view','ویو استوری اینستاگرام',25000],['ig_comment','کامنت اینستاگرام',80000],['ig_save','سیو پست اینستاگرام',45000],['ig_share','اشتراک‌گذاری پست اینستاگرام',40000],['ig_story_like','لایک استوری اینستاگرام',35000],['ig_live','لایک و بازدید لایو اینستاگرام',60000],['ig_explore','خدمات اکسپلور اینستاگرام',70000],['ig_impression','ایمپرشن اینستاگرام',30000],['ig_poll','رأی نظرسنجی اینستاگرام',50000]]},
 Telegram:{icon:'✈',items:[['tg_channel','ممبر کانال تلگرام',180000],['tg_group','ممبر گروه تلگرام',180000],['tg_view','ویو پست تلگرام',25000],['tg_story','ویو استوری تلگرام',30000],['tg_reaction','ری‌اکشن تلگرام',35000],['tg_like','لایک تلگرام',35000],['tg_share','اشتراک‌گذاری تلگرام',30000],['tg_ads','تبلیغات تلگرام',220000],['tg_poll','رأی نظرسنجی تلگرام',40000],['tg_premium','ممبر پرمیوم تلگرام',260000]]},
 Rubika:{icon:'◈',items:[['rb_follow','فالوور روبیکا',140000],['rb_like','لایک روبیکا',30000],['rb_view','ویو روبیکا',20000]]},
 Eitaa:{icon:'✦',items:[['et_channel','ممبر کانال ایتا',150000],['et_group','ممبر گروه ایتا',150000],['et_view','ویو ایتا',20000],['et_ads','تبلیغات ایتا',250000],['et_directory','ثبت کانال ایتا در دایرکتوری',80000]]}
};
const allServices=Object.entries(SERVICES).flatMap(([network,data])=>data.items.map(([id,name,price])=>({id,network,name,price})));
const fmt=n=>new Intl.NumberFormat('fa-IR').format(Math.round(n))+' تومان';
const getOrders=()=>JSON.parse(localStorage.getItem('fc_orders')||'[]');
const saveOrders=o=>localStorage.setItem('fc_orders',JSON.stringify(o));
function toast(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function initNav(){const toggle=document.querySelector('.mobile-toggle'),menu=document.querySelector('.menu');if(toggle)toggle.onclick=()=>menu.classList.toggle('open');const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.menu a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')})}
function serviceCards(limit){const host=document.querySelector('#serviceCards');if(!host)return;host.innerHTML=allServices.slice(0,limit||allServices.length).map(s=>`<a class="card service-card" href="order.html?service=${s.id}"><div class="icon">${SERVICES[s.network].icon}</div><h3>${s.name}</h3><div class="price">${fmt(s.price)} <small>/ 1K</small></div><span class="network">${s.network}</span></a>`).join('')}
function setupOrder(){const network=document.querySelector('#network'),service=document.querySelector('#service'),qty=document.querySelector('#quantity'),total=document.querySelector('#total'),form=document.querySelector('#orderForm');if(!network)return;Object.keys(SERVICES).forEach(n=>network.insertAdjacentHTML('beforeend',`<option value="${n}">${n==='Rubika'?'روبیکا':n==='Eitaa'?'ایتا':n}</option>`));function fill(){service.innerHTML='<option value="">انتخاب سرویس</option>'+(SERVICES[network.value]?.items||[]).map(x=>`<option value="${x[0]}">${x[1]} — ${fmt(x[2])}/1K</option>`).join('');calc()}network.onchange=fill;service.onchange=calc;qty.oninput=calc;function calc(){const s=allServices.find(x=>x.id===service.value),q=Math.max(0,Number(qty.value)||0);total.textContent=s?fmt(s.price*q/1000):'۰ تومان'}const qs=new URLSearchParams(location.search).get('service');if(qs){const s=allServices.find(x=>x.id===qs);if(s){network.value=s.network;fill();service.value=s.id;calc()}}form.onsubmit=e=>{e.preventDefault();const s=allServices.find(x=>x.id===service.value),q=Number(qty.value);if(!s||q<1){toast('لطفاً شبکه، سرویس و تعداد را انتخاب کنید.');return}const order={code:'FC-'+Math.floor(100000+Math.random()*900000),network:s.network,service:s.name,serviceId:s.id,quantity:q,link:document.querySelector('#link').value.trim(),phone:document.querySelector('#phone').value.trim(),notes:document.querySelector('#notes').value.trim(),amount:s.price*q/1000,date:new Date().toISOString(),status:'pending'};if(!order.link||!order.phone){toast('لینک و شماره موبایل را وارد کنید.');return}const orders=getOrders();orders.unshift(order);saveOrders(orders);document.querySelector('#success').innerHTML=`<div class="notice">سفارش با موفقیت ثبت شد. کد پیگیری شما: <strong>${order.code}</strong></div>`;form.reset();fill();total.textContent='۰ تومان';toast('سفارش ثبت شد.')}}
function renderOrders(){const body=document.querySelector('#ordersBody');if(!body)return;const orders=getOrders();const counts={all:orders.length,pending:0,running:0,done:0,cancelled:0};orders.forEach(o=>counts[o.status]++);Object.entries(counts).forEach(([k,v])=>{const el=document.querySelector(`[data-count="${k}"]`);if(el)el.textContent=v.toLocaleString('fa-IR')});body.innerHTML=orders.length?orders.map(o=>`<tr><td><strong>${o.code}</strong></td><td>${o.network}</td><td>${o.service}</td><td>${o.quantity.toLocaleString('fa-IR')}</td><td>${fmt(o.amount)}</td><td>${statusBadge(o.status)}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">هنوز سفارشی ثبت نشده است.</td></tr>`}
function statusBadge(s){return ({pending:'<span class="badge pending">🟡 در انتظار</span>',running:'<span class="badge running">🔵 در حال انجام</span>',done:'<span class="badge done">🟢 تکمیل شده</span>',cancelled:'<span class="badge cancelled">🔴 لغو شده</span>'})[s]||s}
function setupTracking(){const form=document.querySelector('#trackingForm'),result=document.querySelector('#trackingResult');if(!form)return;form.onsubmit=e=>{e.preventDefault();const code=document.querySelector('#code').value.trim().toUpperCase();const o=getOrders().find(x=>x.code===code);result.innerHTML=o?`<div class="panel card"><div class="section-head"><div><h2>${o.code}</h2><span class="muted">${new Date(o.date).toLocaleString('fa-IR')}</span></div>${statusBadge(o.status)}</div><div class="grid"><div><span class="muted">شبکه</span><br><b>${o.network}</b></div><div><span class="muted">سرویس</span><br><b>${o.service}</b></div><div><span class="muted">تعداد</span><br><b>${o.quantity.toLocaleString('fa-IR')}</b></div><div><span class="muted">مبلغ</span><br><b>${fmt(o.amount)}</b></div></div></div>`:`<div class="notice">سفارشی با این کد پیدا نشد. کد را دقیق بررسی کنید.</div>`}}
function inject(){document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());initNav();serviceCards(document.querySelector('#serviceCards')?.dataset.limit?Number(document.querySelector('#serviceCards').dataset.limit):undefined);setupOrder();renderOrders();setupTracking()}
document.addEventListener('DOMContentLoaded',inject);
